--Source: HR_SANDBOX@TEAMWORK2012:1521/ORCL (latest repository revisions)
--Target: HR_DEV@TEAMWORK2012:1521/ORCL 

--Script generated by \ on 12/12/2018 05:44
--Note: Please review this script prior to execution

HOST if not exist "C:\Automation\MP\HumanResources\Spool" mkdir "C:\Automation\MP\HumanResources\Spool"
SPOOL "C:\Automation\MP\HumanResources\Spool\2018-12-12-054418_Output_Spool.log" APPEND

SET SERVEROUTPUT ON
SET DEFINE OFF
SET BLOCKTERMINATOR OFF
SET SQLBLANKLINES ON

PROMPT Fetching invalid objects before deployment actions
PROMPT ****************************************************************************
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM   ALL_OBJECTS
WHERE  STATUS <> 'VALID' AND OWNER = USER;

-- Step 1: Creating columns
EXECUTE DBMS_OUTPUT.PUT_LINE('Step 1: Creating columns');
ALTER TABLE "EMPLOYEES" ADD ("BRADYCOL" VARCHAR2(40 BYTE) DEFAULT NULL);



-- Step 9: Recompiling invalid objects
EXECUTE DBMS_OUTPUT.PUT_LINE('Step 9: Recompiling invalid objects');
BEGIN
DBMS_UTILITY.COMPILE_SCHEMA(USER, FALSE, FALSE);
EXCEPTION
WHEN OTHERS THEN
dbms_output.Put_Line('Waring: Recompile Encountered an Error.');
END;
/


PROMPT Fetching invalid objects after deployment actions
PROMPT ****************************************************************************
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM   ALL_OBJECTS
WHERE  STATUS <> 'VALID' AND OWNER = USER;


SET SQLBLANKLINES OFF
SET BLOCKTERMINATOR ON
SET DEFINE ON
SPOOL OFF




exit;

