##-------------------------------------------------##
## Azure Deploy YAML
resources:
- repo: self

variables:
  Parameters.basePath: '/home/main-admin/devops'
  Parameters.server: 'INT-ubuntu'
  Parameters.userName: 'main_admin'
  Parameters.password: 'jkaj5kldfj6jkgj23k6llgsl'

stages:
- stage: deploy
  jobs:
  - deployment: DeployDB
    displayName: deploy Atlas
    pool: atlas_script_node
    environment: 'INT'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo Deploying Atlas via API
              cd /home/main-admin/devops
              /usr/bin/python3.7 atlas_rest.py action=cluster_info
            displayName: Atlas cluster info
